# Generated by Django 3.1.1 on 2020-09-15 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refId', models.TextField(max_length=15)),
                ('transType', models.TextField(max_length=64)),
                ('desc', models.TextField(max_length=254, null=True)),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('updatedAt', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.TextField(max_length=20)),
                ('balance', models.IntegerField(default=0)),
                ('isDeleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='created_at')),
                ('updatedAt', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.user')),
            ],
        ),
    ]
